### PR TITLE
Fix access to other storages in leanback

### PR DESCRIPTION
**Pull request by ghost**
Not tested
Current behavior : when trying to access other storages, open local storage instead

### CODE REVIEW

**Comment by courville** [comment]
Thank you for your contribution: I am not sure that this would resolve any issue.
Could you please test the patch and provide feedback?

**Comment by ghost** [comment]
I tested it and it works. Other external storages are now accessible.

**Comment by courville** [comment]
The modification you propose suppresses ability to browse Internal file storage.
When an external USB key is inserted it should be detected via updateUsbAndSdcardVisibility() in MainFragment.java. If you do not see external storage (I do on my nvidia shield) this means that storageManager.hasExtStorage() is broken and this is a bug.
Can you please disclose your hardware configuration and Android version?
Thank you.

**Comment by courville** [comment]
Another question: what is the type of storage that is not displayed on your box? This could help tracking the issue.

**Comment by ghost** [comment]
I will try to explain the issue I experienced. I have a SHIELD TV on latest firmware and it is connected to a network share at system level. In Nova, it appears as an external storage. The issue was that when I tried to access the content of this external storage on the leanback interface, it was the content of the internal storage that was displayed instead. I looked at the source code and have seen that the "other" type of external storage had the the same Box.ID as internal storage.
When I tested the patch, internal storage was still accessible.

**Pull request merged**
