### PR TITLE
Update Italian Translation

### PR DESCRIPTION
**Pull request by DaFlowah**
Entire new Italian translation made from scratch.

### CODE REVIEW

**Comment by courville** [comment]
Andrea, thank you for your contribution!
I will upload the resource file to crowdin https://crowdin.com/project/nova-video-player where I try to host all the translation efforts. If you feel up to it there are two other translation files in MediaLib and FileCoreLibrary.

**Comment by DaFlowah** [comment]
Yeah, sadly I didn't notice the Crowdin note on time, nevermind.
Anyway, I'll give a look to the other files as soon as I can ;D

**Review by DaFlowah — COMMENTED** [review]
Minor fixes in my translation.

**Comment by courville** [comment]
I will upload the translation file to replace the current on on crowdin.

**Comment by courville** [comment]
Done: https://crowdin.com/project/nova-video-player/it# (still 3% missing for some reasons).
Please review and for each conflict in FileCoreLibrary and MediaLib you found, please use your proposition. Thanks again!

**Comment by courville** [comment]
I will generate a beta this week including your changes, if you want to try it out please subscribe to https://play.google.com/apps/testing/org.courville.nova (unless you are using your own build).

**Comment by DaFlowah** [comment]
Done. I made some extra little changes.
In the next days I will further review my own translation in Video and, why not, the Google page as well.
Hope I didn't cause you too much mess with all my changes 😅
Hope I've done everything properly. Dunno if I can use use Crowdin properly (first time I'm translating on that portal), but should be pretty intuitive.
Anyway, I'm gonna join the beta immediatly, thank you!

**Pull request merged**
