### PR TITLE
Writer TAG added for Movies & Episodes

### PR DESCRIPTION
**Pull request by bronnel**

### CODE REVIEW

**Comment by courville** [comment]
Thanks, it would be nice to get these modifications reflected back in the leanback UI as well.
On a more general comment, there has been enhancements in the UI for displaying actors etc. in the leanback UI that has not been ported back to the phone/tablet UI.

**Comment by bronnel** [comment]
> Thanks, it would be nice to get these modifications reflected back in the leanback UI as well. On a more general comment, there has been enhancements in the UI for displaying actors etc. in the leanback UI that has not been ported back to the phone/tablet UI.

leanback UI will definitely get the love it deserves, But right now I will focus on the Phone/Tablet mode, once this is done , I think it is very easy to implement changes to leanback.

**Comment by courville** [comment]
Sorry but still some errors when upgrading:
```
2022-02-11 21:27:19.876 30040-30318/org.courville.nova E/com.archos.mediaprovider.video.VideoStoreImportService: SQLException or IllegalStateException
    android.database.sqlite.SQLiteException: no such table: writer (code 1 SQLITE_ERROR): , while compiling: delete from writer where _id in (select _id from v_writer_deletable)
        at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
        at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1047)
        at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:654)
        at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:590)
        at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:62)
        at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:34)
        at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1920)
        at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1842)
        at com.archos.mediaprovider.video.VideoStoreImportService.processDeleteFileAndVobCallback(VideoStoreImportService.java:458)
        at com.archos.mediaprovider.video.VideoStoreImportService.doImport(VideoStoreImportService.java:436)
        at com.archos.mediaprovider.video.VideoStoreImportService.handleMessage(VideoStoreImportService.java:375)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.os.HandlerThread.run(HandlerThread.java:67)
```

**Comment by bronnel** [comment]
@courville thanks ,I will check it

**Comment by courville** [comment]
Thanks for the premiered date displayed. One issue is that it is too long in some cases (I think we can skip `Premiered:` string).
Moreover in general never use a hardcoded string in english (Premiered:) since we want it translated and link it to the @string/ref (in this case I suggest to not use a string for space saving).
screen

**Comment by courville** [comment]
A part of your pull request has been already merged and pushed to nova please rebase your branch on latest v6.

**Comment by bronnel** [comment]
> Thanks for the premiered date displayed. One issue is that it is too long in some cases (I think we can skip `Premiered:` string). Moreover in general never use a hardcoded string in english (Premiered:) since we want it translated and link it to the @string/ref (in this case I suggest to not use a string for space saving). 


@courville , The location of these is temorary I will find a better place for it , I don't plan to get rid of it, but In the final UI transition , there will be even more tags

**Comment by courville** [comment]
All the commits have been cherry-picked and merged.

**Pull request closed without merging**
